steps:

  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA","-t", "gcr.io/$PROJECT_ID/$REPO_NAME:latest", "--network=cloudbuild", "."]

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "--all-tags", "gcr.io/$PROJECT_ID/$REPO_NAME"]

  - id: "apply db migrations"
    name: "gcr.io/google-appengine/exec-wrapper"
    args:
      [
        "-i",
        "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA",
        "-e",
        "SETTINGS_NAME=${_SECRET_SETTINGS_NAME}",
        "-e",
        "PORT=8000",
        "--",
        "python",
        "manage.py",
        "migrate",
      ]

  - id: "bootstrap database with data"
    name:
    name: "gcr.io/google-appengine/exec-wrapper"
    args:
      [
        "-i",
        "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA",
        "-e",
        "SETTINGS_NAME=${_SECRET_SETTINGS_NAME}",
        "-e",
        "PORT=8000",
        "--",
        "make",
        "bootstrap-db",
      ]


    # Deploy container image to Cloud Run
  - id: "deploy new image to cloud run"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', '${_SERVICE_NAME}', '--image', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest', '--region', '${_REGION}', '--platform', 'managed']

substitutions:
  _REGION: us-central1
  _SERVICE_NAME: website 
  _SECRET_SETTINGS_NAME: website_django_secrets

images:
  - gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY

