steps:

  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA", "--network=cloudbuild", "."]
    secretsManager:
      - versionName: projects/${PROJECT_ID}/secrets/website_django_secrets/versions/latest
        env: 'WEBSITE_DJANGO_SECRETS'

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"]

  - id: "apply db migrations"
    name: "gcr.io/google-appengine/exec-wrapper"
    args:
      [
        "-i",
        "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA",
        "-s",
        "${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}",
        "-e",
        "SETTINGS_NAME=${_SECRET_SETTINGS_NAME}",
        "--",
        "python",
        "manage.py",
        "migrate",
      ]

substitutions:
  _INSTANCE_NAME: django-instance
  _REGION: us-central1
  _SERVICE_NAME: website 
  _SECRET_SETTINGS_NAME: website_django_secrets

images:
  - gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
