# Generated by Django 5.0.3 on 2024-03-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_thing_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thing',
        ),
    ]
