# Generated by Django 5.0.3 on 2024-03-30 19:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Degree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(max_length=200)),
                ("degree_name", models.CharField(max_length=200)),
                ("completion_month", models.IntegerField()),
                ("completion_year", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("tagline", models.TextField()),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200), size=None
                    ),
                ),
                ("start_month", models.IntegerField()),
                ("end_month", models.IntegerField()),
                ("start_year", models.IntegerField()),
                ("end_year", models.IntegerField()),
                ("is_current", models.BooleanField(default=False)),
            ],
        ),
    ]
